impedance_node:
  ros__parameters:
    base_link: "base_link"
    end_effector: "gripper_tcp"
    joint_names: ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6"]
    stiffness: [400.0, 400.0, 400.0, 20.0, 20.0, 20.0]
    damping: [40.0, 40.0, 40.0, 2.0, 2.0, 2.0]
